@echo off
REM ========================================================================
REM OrcaSlicer x64 Build Script
REM Run this file directly from Windows Explorer or Command Prompt
REM ========================================================================

setlocal enabledelayedexpansion
color 0A
title OrcaSlicer Build

echo.
echo ========================================================================
echo  OrcaSlicer x64 Build Script
echo ========================================================================
echo.
echo This script will:
echo   1. Clean the build directory
echo   2. Set up Visual Studio 2022 x64 environment
echo   3. Configure the project with CMake
echo   4. Build OrcaSlicer
echo.
echo Build will take 15-30 minutes depending on your system.
echo.
pause

REM Navigate to project root
cd /d "%~dp0"
echo Working directory: %CD%
echo.

REM Step 1: Clean build directory
echo ========================================================================
echo STEP 1: Cleaning build directory...
echo ========================================================================
if exist build (
    echo Removing old build directory...
    rmdir /s /q build 2>nul
    if exist build (
        echo WARNING: Could not fully clean build directory. Proceeding anyway...
    )
)
mkdir build
echo Build directory ready.
echo.

REM Step 2: Set up Visual Studio environment
echo ========================================================================
echo STEP 2: Setting up Visual Studio 2022 x64 environment...
echo ========================================================================
set VS2022_VCVARS=J:\visualstudio\vs2022\VC\Auxiliary\Build\vcvarsall.bat

if not exist "%VS2022_VCVARS%" (
    echo ERROR: Cannot find Visual Studio 2022 vcvarsall.bat
    echo Expected location: %VS2022_VCVARS%
    echo.
    echo Please verify Visual Studio 2022 is installed correctly.
    pause
    exit /b 1
)

call "%VS2022_VCVARS%" x64
if !ERRORLEVEL! NEQ 0 (
    echo ERROR: Failed to initialize Visual Studio environment
    pause
    exit /b 1
)
echo Visual Studio 2022 x64 environment initialized successfully.
echo.

REM Step 3: Configure with CMake
echo ========================================================================
echo STEP 3: Configuring project with CMake...
echo ========================================================================
cd build
set CMAKE_EXE=%~dp0tools\cmake-3.31.5-windows-x86_64\bin\cmake.exe

if not exist "%CMAKE_EXE%" (
    echo ERROR: Cannot find CMake
    echo Expected location: %CMAKE_EXE%
    pause
    exit /b 1
)

echo Running CMake configure...
"%CMAKE_EXE%" .. -G "Ninja" -DCMAKE_BUILD_TYPE=Release
set CMAKE_EXIT=!ERRORLEVEL!

if !CMAKE_EXIT! NEQ 0 (
    echo.
    echo ========================================================================
    echo ERROR: CMake configuration failed with exit code !CMAKE_EXIT!
    echo ========================================================================
    echo.
    echo This usually means:
    echo   - Missing dependencies (OpenSSL, CURL, wxWidgets, etc.)
    echo   - Environment setup issues
    echo.
    echo Check the error messages above for details.
    echo.
    pause
    exit /b !CMAKE_EXIT!
)

echo CMake configuration completed successfully.
echo.

REM Check if build.ninja was generated
if not exist build.ninja (
    echo ERROR: build.ninja was not generated by CMake
    echo Configuration may have failed silently.
    pause
    exit /b 1
)

REM Step 4: Build the project
echo ========================================================================
echo STEP 4: Building OrcaSlicer...
echo ========================================================================
echo.
echo This will take 15-30 minutes. Please be patient...
echo Build started at: %TIME%
echo.

"%CMAKE_EXE%" --build . --config Release
set BUILD_EXIT=!ERRORLEVEL!

echo.
echo Build finished at: %TIME%
echo.

if !BUILD_EXIT! NEQ 0 (
    echo ========================================================================
    echo BUILD FAILED with exit code !BUILD_EXIT!
    echo ========================================================================
    echo.
    echo Check the error messages above for details.
    echo Common issues:
    echo   - Missing header files (OpenSSL, CURL, OpenCV)
    echo   - Precompiled header cache issues
    echo   - Missing library dependencies
    echo.
    pause
    exit /b !BUILD_EXIT!
)

echo ========================================================================
echo BUILD SUCCESSFUL!
echo ========================================================================
echo.
echo Executable location:
echo   %~dp0build\src\OrcaSlicer.exe
echo.
echo Build artifacts are in:
echo   %~dp0build\
echo.
echo.

pause
exit /b 0
